#!/usr/bin/env bash
# capture.sh — regenerate this repo's manifests from the live machine.
#
# This is what stops the rebuild script from quietly rotting. Run it whenever
# you install something you would miss, and commit the diff. Reading that diff
# is also a decent monthly review of what has crept onto your machine.
#
#   ./capture.sh            refresh manifests
#   ./capture.sh --payload  also copy Claude Code config into files/claude/
#
# ── On secrets ────────────────────────────────────────────────────────────
# Manifests record names and versions, never values. The one file that mixes
# the two is ~/.claude/settings.json, whose hook commands embed a monitor token
# inline; --payload copies it with that token replaced by __SET_ME__.
#
# --payload also copies your Claude commands and skills, which contain your own
# business logic. That is why it is opt-in rather than default: check whether
# this repo's remote is private before you commit the result.

set -uo pipefail

LAPTOP_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
. "${LAPTOP_DIR}/lib/common.sh"
. "${LAPTOP_DIR}/lib/distro.sh"

MAN="${LAPTOP_DIR}/manifests"
PAYLOAD="${LAPTOP_DIR}/files/claude"
WITH_PAYLOAD=0
[[ "${1:-}" == "--payload" ]] && WITH_PAYLOAD=1

mkdir -p "$MAN"
detect_distro

# Header without a timestamp: a timestamp alone would make every file show as
# changed on every run, which buries the diff that actually matters.
hdr() { printf '# %s\n# generated by capture.sh on %s\n\n' "$1" "$DISTRO_NAME"; }

heading "Capturing manifests"

# ------------------------------------------------------------- packages ----

step "manifest: apt manual packages"
if have apt-mark; then
  { hdr "Explicitly-installed packages. Restore: xargs -a this-file sudo apt-get install -y"
    apt-mark showmanual 2>/dev/null | sort
  } > "$MAN/apt-manual.txt"
  mark_ok "manifest: apt-manual.txt ($(grep -vc '^#' "$MAN/apt-manual.txt") packages)"
elif have rpm; then
  { hdr "User-installed rpm packages"; dnf repoquery --userinstalled --qf '%{name}' 2>/dev/null | sort; } > "$MAN/rpm-manual.txt"
  mark_ok "manifest: rpm-manual.txt"
elif have pacman; then
  { hdr "Explicitly-installed pacman packages"; pacman -Qqe | sort; } > "$MAN/pacman-manual.txt"
  mark_ok "manifest: pacman-manual.txt"
else
  mark_skip "manifest: packages" "no known package manager"
fi

step "manifest: third-party apt repos"
if [[ -d /etc/apt/sources.list.d ]]; then
  { hdr "Third-party apt repositories and their signing keys"
    for f in /etc/apt/sources.list.d/*; do
      [[ -f "$f" ]] || continue
      printf '### %s\n' "$f"
      grep -vE '^\s*(#|$)' "$f" 2>/dev/null
      printf '\n'
    done
    printf '### keyrings\n'
    ls -1 /etc/apt/keyrings/ /usr/share/keyrings/ 2>/dev/null | sort -u
  } > "$MAN/apt-sources.txt"
  mark_ok "manifest: apt-sources.txt"
else
  mark_skip "manifest: third-party apt repos" "not an apt system"
fi

# ------------------------------------------------------------ toolchains ----

step "manifest: node and npm globals"
{ hdr "Node versions and global packages"
  if [[ -d "$HOME/.nvm/versions/node" ]]; then
    printf '## nvm versions\n'
    ls -1 "$HOME/.nvm/versions/node" 2>/dev/null
    printf '\n## default alias\n'
    cat "$HOME/.nvm/alias/default" 2>/dev/null
    printf '\n'
  fi
  printf '\n## global packages (current default node)\n'
  if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
    bash -c '. "$HOME/.nvm/nvm.sh" >/dev/null 2>&1 && npm ls -g --depth=0 2>/dev/null' \
      | sed '1d' | sed 's/^[├└─│ ]*//' | grep -v '^$'
  elif have npm; then
    npm ls -g --depth=0 2>/dev/null | sed '1d' | sed 's/^[├└─│ ]*//' | grep -v '^$'
  fi
} > "$MAN/node.txt"
mark_ok "manifest: node.txt"

step "manifest: python tooling"
{ hdr "Python: interpreters and tool installs"
  printf '## system\n'; python3 --version 2>&1
  printf '\n## uv tools\n';   have uv    && uv tool list 2>/dev/null
  printf '\n## uv pythons\n'; have uv    && uv python list --only-installed 2>/dev/null
  printf '\n## pipx\n';       have pipx  && pipx list --short 2>/dev/null
  printf '\n## pyenv\n';      [[ -d "$HOME/.pyenv/versions" ]] && ls -1 "$HOME/.pyenv/versions" 2>/dev/null
  printf '\n## pip --user\n'; python3 -m pip list --user --format=freeze 2>/dev/null
} > "$MAN/python.txt"
mark_ok "manifest: python.txt"

step "manifest: ruby"
{ hdr "Ruby: rubies and notable gems"
  if [[ -d "$HOME/.rvm/rubies" ]]; then
    printf '## rvm rubies\n'; ls -1 "$HOME/.rvm/rubies" 2>/dev/null
    printf '\n## default\n';  cat "$HOME/.rvm/config/alias" 2>/dev/null
  fi
  printf '\n## gems (default ruby)\n'
  have gem && gem list --local --no-versions 2>/dev/null | grep -v '^$'
} > "$MAN/ruby.txt"
mark_ok "manifest: ruby.txt"

step "manifest: hand-installed binaries"
{ hdr "Binaries not managed by any package manager — the silent-loss list"
  for d in /usr/local/bin "$HOME/.local/bin" /opt; do
    [[ -d "$d" ]] || continue
    printf '## %s\n' "$d"
    find "$d" -maxdepth 1 -type f -executable -printf '%f\n' 2>/dev/null | sort
    find "$d" -maxdepth 1 -type l -printf '%f -> %l\n' 2>/dev/null | sort
    printf '\n'
  done
} > "$MAN/local-binaries.txt"
mark_ok "manifest: local-binaries.txt"

# ------------------------------------------------------ services + ports ----

step "manifest: services"
if have systemctl; then
  { hdr "Enabled units and active listeners"
    printf '## enabled units\n'
    systemctl list-unit-files --state=enabled --no-pager --no-legend 2>/dev/null | awk '{print $1}' | sort
    printf '\n## custom units in /etc/systemd/system\n'
    find /etc/systemd/system -maxdepth 1 -type f -name '*.service' -o -maxdepth 1 -type f -name '*.timer' 2>/dev/null | sort
    printf '\n## timers\n'
    systemctl list-timers --all --no-pager --no-legend 2>/dev/null | awk '{print $NF}' | sort -u
  } > "$MAN/services.txt"
  mark_ok "manifest: services.txt"
else
  mark_skip "manifest: services" "no systemctl"
fi

step "manifest: listening ports"
{ hdr "Listening sockets. Anything on 0.0.0.0 is reachable from the Windows host."
  (ss -tulpnH 2>/dev/null || netstat -tulpn 2>/dev/null) | awk '{print $1, $5, $7}' | sort -u
} > "$MAN/ports.txt"
mark_ok "manifest: ports.txt"

# ------------------------------------------------------------ postgres ----

step "manifest: postgres databases"
if have psql && psql -lqt >/dev/null 2>&1; then
  { hdr "Databases (names and owners only — never contents)"
    psql -lqt 2>/dev/null | awk -F'|' 'NF>2 {gsub(/^ +| +$/,"",$1); gsub(/^ +| +$/,"",$2); if ($1!="") print $1" (owner: "$2")"}'
    printf '\n## NOTE\n'
    printf '# A database with datallowconn=false is silently skipped by pg_dumpall.\n'
    printf '# Check for them: psql -tAc "SELECT datname FROM pg_database WHERE NOT datallowconn"\n'
  } > "$MAN/postgres-databases.txt"
  mark_ok "manifest: postgres-databases.txt"
else
  mark_skip "manifest: postgres databases" "psql unavailable or not connectable"
fi

# ---------------------------------------------------------------- repos ----

step "manifest: git repositories"
{ hdr "Repositories, their remotes, and their risk state"
  printf '%-52s %-28s %-46s %s\n' "PATH" "BRANCH" "REMOTE" "RISK"
  while IFS= read -r gitdir; do
    repo="${gitdir%/.git}"
    branch="$(git -C "$repo" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
    remote="$(git -C "$repo" remote get-url origin 2>/dev/null || echo 'NO-REMOTE')"
    risk=""
    if ! git -C "$repo" rev-parse HEAD >/dev/null 2>&1; then
      risk="NO-COMMITS"
    else
      [[ "$remote" == "NO-REMOTE" ]] && risk="NO-REMOTE"
      unpushed="$(git -C "$repo" log --branches --not --remotes --oneline 2>/dev/null | wc -l)"
      ((unpushed > 0)) && risk="${risk:+$risk,}UNPUSHED:$unpushed"
    fi
    dirty="$(git -C "$repo" status --porcelain 2>/dev/null | wc -l)"
    ((dirty > 0)) && risk="${risk:+$risk,}DIRTY:$dirty"
    printf '%-52s %-28s %-46s %s\n' "${repo/#$HOME/\~}" "$branch" "$remote" "${risk:-ok}"
  done < <(find "$HOME" -maxdepth 3 -name .git -type d -not -path '*/node_modules/*' 2>/dev/null | sort)
} > "$MAN/repos.txt"
mark_ok "manifest: repos.txt ($(grep -c 'NO-REMOTE\|NO-COMMITS\|UNPUSHED' "$MAN/repos.txt" 2>/dev/null || echo 0) at risk)"

# -------------------------------------------------------------- payload ----

if ((WITH_PAYLOAD)); then
  step "payload: Claude Code config"
  mkdir -p "$PAYLOAD"

  if [[ -f "$HOME/.claude/settings.json" ]]; then
    # Strip the inline monitor token. Matches KEY=<value> inside hook command
    # strings, which is where it lives.
    sed -E 's/(CLAUDE_MONITOR_TOKEN=)[A-Za-z0-9_-]+/\1__SET_ME__/g' \
      "$HOME/.claude/settings.json" > "$PAYLOAD/settings.json"
    if grep -qE '(TOKEN|SECRET|KEY|PASSWORD)=[A-Za-z0-9_-]{12,}' "$PAYLOAD/settings.json"; then
      warn "settings.json may still contain a credential after redaction — inspect $PAYLOAD/settings.json before committing"
    fi
    mark_ok "payload: settings.json (token redacted)"
  else
    mark_skip "payload: settings.json" "not present"
  fi

  for sub in commands skills lib; do
    if [[ -d "$HOME/.claude/$sub" ]] && [[ -n "$(ls -A "$HOME/.claude/$sub" 2>/dev/null)" ]]; then
      mkdir -p "$PAYLOAD/$sub"
      cp -r "$HOME/.claude/$sub/." "$PAYLOAD/$sub/"
      mark_ok "payload: $sub ($(find "$PAYLOAD/$sub" -type f | wc -l) files)"
    else
      mark_skip "payload: $sub" "empty or absent"
    fi
  done

  [[ -f "$HOME/.inputrc" ]] && cp "$HOME/.inputrc" "${LAPTOP_DIR}/files/inputrc" \
    && mark_ok "payload: inputrc"

  manual "Payload copied. Check 'git diff' before committing — commands/ and skills/ contain your own business logic."
else
  note "Claude payload not captured. Re-run with --payload to include it."
fi

summary
